import Head from 'next/head'
import NavBar from '../components/Shared/NavBar'


export default function Home() {
  return (
  <>

  <Head>
        <title>Canvas-Hawker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      </main>
  </>
  )
}
